### ISSUE TITLE
Subalbums and password protection

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-Laravel#139]
Album-level password protection doesn't seem to work in combination with subalbums.

I first tried a password-protected top-level album with a public sub-album. In public mode (not logged in), providing the password opened the top-level album as expected, but clicking on the sub-album wasn't working. JS console had a `TypeError: albums.getByID(...) is undefined` error logged.

I tried the opposite combination: an unprotected top-level album with a password-protected subalbum. That didn't work either: clicking on the subalbum results in an empty album view and, eventually, same JS error. More worrying, the subalbum was not marked as password protected and the thumbs of the three pictures inside were displayed, so it loks like the server was only too happy to serve them -- without a password being provided.

Looking at the source code, it looks like at least `albums.getByID()` has no support for subalbums (I guess it would need to descend recursively in search for an album ID?).

My basic question though would be: is this even supposed to work? I can imagine that with Lychee-Laravel being multi-user, perhaps password protection at the album level is seen as an anachronism? A similar effect could, I'm guessing, be achieved by sharing an album/subalbums with a password-protected, locked, read-only "guest" account. So let me know if you even want to be bothered with such reports...

**Comment by ildyria** [comment]
Fixed.

**Comment by joszz** [comment]
This seems to still not work properly?
I also wanted to password protect an album with subalbums.
After logging in with the password no subalbums are displayed

**Comment by d7415** [comment]
> After logging in with the password no subalbums are displayed

Have you set the subalbums to public? (with or without password)

**Comment by joszz** [comment]
Well yes, if I set the subalbums to public it will show.
It would be handy though that I could inherit the password protection (or all other visibility properties for that mather) from the top album.
Now if I want to properly protect this album and it's subalbums, a user would have to provide the password constantly when navigating through album and then subalbum. Bit of a bad user experience. Although it might make sense to do this, having different passwords set for different sub albums for some use cases.
Maybe not really a bug, but also not the best solution for everybody. 

If I set the album to hidden it will be invisible from the top album (which makes sense I guess, it does what it says it does, only accessible through direct link).

p.s.
I'm on latest Lychee 4.0.4

**Comment by ildyria** [comment]
> It would be handy though that I could inherit the password protection (or all other visibility properties for that mather) from the top album.

This is somewhat already the case. In order to access the sub album directly you still need to provide the password for the parent.

> Now if I want to properly protect this album and it's subalbums, a user would have to provide the password constantly when navigating through album and then subalbum. Bit of a bad user experience. Although it might make sense to do this, having different passwords set for different sub albums for some use cases.

This is already implemented: we record in your cookies which albums (with password protection) you were given access to so that you don't have to provide a password every time.

> If I set the album to hidden it will be invisible from the top album (which makes sense I guess, it does what it says it does, only accessible through direct link).

Yes.

> p.s.
> I'm on latest Lychee 4.0.4

:hugs:

**Comment by Eisteed** [comment]
Hey, just bumping this thread because I have the same issue, creating a password protected album is working as intended but sub-albumb need to be public to be displayed and then direct link to the sub album is working without any password :/

**Comment by kamil4** [comment]
This was fixed in #727 and included in Lychee 4.0.7. Basically, the currently recommended solution is to set the same password for the subalbums as for the main album. When you enter a correct password for an album, Lychee will try that password against all other password-protected albums and, if the password matches, unlock them.

It's a little tedious right now because you'll need to set the password individually for each subalbum. In the future we will provide an option to propagate the visibility changes to subalbums with one click.

P.S. In the future, I recommend that you open a new issue rather than add comments to long closed ones.
