### ISSUE TITLE
Unable to import some JPGs

### ISSUE THREAD

**Issue by gardiol** [LycheeOrg/Lychee-Laravel#451]
### Detailed description of the problem

Try to import attached file fails. Only error displayed is the classic red error line on top of the page (Loading failed unknown error...). Nothing appears in the logs too!

I have a lot of these files. They seems to be perfectly fine opening with any image program. Also, they come from the same camera, one before and one after imports correctly, not this one (and a few others too.. but i am going to upload just a couple)

### Steps to reproduce the issue

Import attached file

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      No git data found. Probably installed from release or could not read .git
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.2
    MySQL Version:             10.2.29-MariaDB-log
    
    Lychee total space:        70.40 MB
    Upload folder space:       43.00 B
    System total space:        411.20 GB
    System free space:         52.69 GB (12%)
    
    Imagick:                   -
    Imagick Active:            1
    Imagick Version:           -
    GD Version:                bundled (2.1.0 compatible)

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         0
    sorting_Photos_col:        title
    sorting_Photos_order:      ASC
    sorting_Albums_col:        title
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      it
    layout:                    1
    image_overlay:             1
    image_overlay_type:        desc
    default_license:           reserved
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 1
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  1
    medium_2x:                 1
    landing_page_enable:       1
    landing_owner:             Willy Gardiol
    landing_title:             Willy Gardiol Photos
    landing_subtitle:          Foto di Willy Gardiol
  landing_facebook:          
    landing_flickr:            
    landing_twitter:           
    landing_instagram:         
    landing_youtube:           
    landing_background:        dist/cat.jpg
    site_title:                Willy Gardiol Photos
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1
    map_display:               1
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              0
    share_button_visible:      0
    has_ffmpeg:                0

![DSC_8323](https://user-images.githubusercontent.com/6368916/76087035-a29ae180-5fb5-11ea-950b-663224753bd3.JPG)
![SDC14982](https://user-images.githubusercontent.com/6368916/76087041-a3cc0e80-5fb5-11ea-8abb-3af0900b8b3e.JPG)

### Browser and system

I have imagemagick and PHP 7.2 installed on my server. Im using firefox on linux.

**Comment by tmp-hallenser** [comment]
Just quickly tested it myself. Seems to be an issue with special characters in your tags.

@ildyria Do you have any experience with special characters, encoding etc? (I don't)

```
PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xD4v\xF4rha...' for column `lychee`.`logs`.`text` at row 1 in /html/Lychee-Laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121
Stack trace:
#0 /html/Lychee-Laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(121): PDOStatement->execute(NULL)
#1 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(463): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `lo...', Array)
#3 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `lo...', Array, Object(Closure))
#4 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\Database\Connection->run('insert into `lo...', Array, Object(Closure))
#5 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->statement('insert into `lo...', Array)
#6 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `lo...', Array)
#7 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2678): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `lo...', Array, 'id')
#8 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(765): Illuminate\Database\Eloquent\Model->save()
#13 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Logs))
#14 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(766): tap(Object(App\Logs), Object(Closure))
#15 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->create(Array)
#16 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'create', Array)
#17 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1632): Illuminate\Database\Eloquent\Model->__call('create', Array)
#18 /html/Lychee-Laravel/app/Logs.php(108): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#19 /html/Lychee-Laravel/app/ModelFunctions/PhotoFunctions.php(692): App\Logs::error('App\\ModelFuncti...', '692', 'Something went ...')
#20 /html/Lychee-Laravel/app/ModelFunctions/PhotoFunctions.php(495): App\ModelFunctions\PhotoFunctions->save(Object(App\Photo), 15818339317370)
#21 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add(Array, 15818339317370, false, true)
#22 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(365): App\Http\Controllers\ImportController->photo('/uploads/import...', false, 15818339317370, true)
#23 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(398): App\Http\Controllers\ImportController->server_exec('/uploads/import...', 15818339317370, false, true, Array)
#24 /html/Lychee-Laravel/app/Console/Commands/sync.php(85): App\Http\Controllers\ImportController->server_exec('/uploads/import', 0, false, true)
#25 [internal function]: App\Console\Commands\sync->handle()
#26 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#27 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#29 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#30 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#31 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#32 /html/Lychee-Laravel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#33 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#34 /html/Lychee-Laravel/vendor/symfony/console/Application.php(1012): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /html/Lychee-Laravel/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /html/Lychee-Laravel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /html/Lychee-Laravel/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xD4v\xF4rha...' for column `lychee`.`logs`.`text` at row 1 in /html/Lychee-Laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123
Stack trace:
#0 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(463): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `lo...', Array)
#2 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `lo...', Array, Object(Closure))
#3 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\Database\Connection->run('insert into `lo...', Array, Object(Closure))
#4 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->statement('insert into `lo...', Array)
#5 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `lo...', Array)
#6 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2678): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `lo...', Array, 'id')
#7 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(765): Illuminate\Database\Eloquent\Model->save()
#12 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Logs))
#13 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(766): tap(Object(App\Logs), Object(Closure))
#14 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->create(Array)
#15 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'create', Array)
#16 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1632): Illuminate\Database\Eloquent\Model->__call('create', Array)
#17 /html/Lychee-Laravel/app/Logs.php(108): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#18 /html/Lychee-Laravel/app/ModelFunctions/PhotoFunctions.php(692): App\Logs::error('App\\ModelFuncti...', '692', 'Something went ...')
#19 /html/Lychee-Laravel/app/ModelFunctions/PhotoFunctions.php(495): App\ModelFunctions\PhotoFunctions->save(Object(App\Photo), 15818339317370)
#20 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add(Array, 15818339317370, false, true)
#21 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(365): App\Http\Controllers\ImportController->photo('/uploads/import...', false, 15818339317370, true)
#22 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(398): App\Http\Controllers\ImportController->server_exec('/uploads/import...', 15818339317370, false, true, Array)
#23 /html/Lychee-Laravel/app/Console/Commands/sync.php(85): App\Http\Controllers\ImportController->server_exec('/uploads/import', 0, false, true)
#24 [internal function]: App\Console\Commands\sync->handle()
#25 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#26 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#28 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#29 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#30 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#31 /html/Lychee-Laravel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#33 /html/Lychee-Laravel/vendor/symfony/console/Application.php(1012): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /html/Lychee-Laravel/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /html/Lychee-Laravel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /html/Lychee-Laravel/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 {main}

Next Illuminate\Database\QueryException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xD4v\xF4rha...' for column `lychee`.`logs`.`text` at row 1 (SQL: insert into `logs` (`type`, `function`, `line`, `text`, `updated_at`, `created_at`) values (error, App\ModelFunctions\PhotoFunctions::save, 692, Something went wrong, error 22007, SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xD4v\xF4rha...' for column `lychee`.`photos`.`tags` at row 1 (SQL: insert into `photos` (`id`, `checksum`, `title`, `url`, `description`, `tags`, `width`, `height`, `type`, `size`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `takestamp`, `latitude`, `longitude`, `altitude`, `imgDirection`, `livePhotoContentID`, `public`, `star`, `album_id`, `owner_id`, `thumb2x`, `thumbUrl`, `small`, `updated_at`, `created_at`) values (15835063513764, 61cd56b81bdf727dc158b33cb42d5783cec9f626, 76087035-a29ae180-5fb5-11ea-950b-663224753bd3, eba0abb32edc049def913aec383f3c77.JPG, Willy Gardiol                       , ??????,Mongolia,?v?rhangaj,??????, 1280, 850, image/jpeg, 196.6 KB, 200, f/13.0, NIKON CORPORATION, NIKON D5000, , 1/640 s, 44 mm, 2011-08-17 16:39:37, 46.898392, 102.76863098333, 1633, ?, ?, 0, 0, 15818339317370, 0, 1, eba0abb32edc049def913aec383f3c77.jpeg, 542x360, 2020-03-06 14:52:32, 2020-03-06 14:52:32)), 2020-03-06 14:52:32, 2020-03-06 14:52:32)) in /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
Stack trace:
#0 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `lo...', Array, Object(Closure))
#1 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\Database\Connection->run('insert into `lo...', Array, Object(Closure))
#2 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->statement('insert into `lo...', Array)
#3 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `lo...', Array)
#4 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2678): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `lo...', Array, 'id')
#5 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(765): Illuminate\Database\Eloquent\Model->save()
#10 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Logs))
#11 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(766): tap(Object(App\Logs), Object(Closure))
#12 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->create(Array)
#13 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'create', Array)
#14 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1632): Illuminate\Database\Eloquent\Model->__call('create', Array)
#15 /html/Lychee-Laravel/app/Logs.php(108): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#16 /html/Lychee-Laravel/app/ModelFunctions/PhotoFunctions.php(692): App\Logs::error('App\\ModelFuncti...', '692', 'Something went ...')
#17 /html/Lychee-Laravel/app/ModelFunctions/PhotoFunctions.php(495): App\ModelFunctions\PhotoFunctions->save(Object(App\Photo), 15818339317370)
#18 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add(Array, 15818339317370, false, true)
#19 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(365): App\Http\Controllers\ImportController->photo('/uploads/import...', false, 15818339317370, true)
#20 /html/Lychee-Laravel/app/Http/Controllers/ImportController.php(398): App\Http\Controllers\ImportController->server_exec('/uploads/import...', 15818339317370, false, true, Array)
#21 /html/Lychee-Laravel/app/Console/Commands/sync.php(85): App\Http\Controllers\ImportController->server_exec('/uploads/import', 0, false, true)
#22 [internal function]: App\Console\Commands\sync->handle()
#23 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#24 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#26 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#29 /html/Lychee-Laravel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /html/Lychee-Laravel/vendor/symfony/console/Application.php(1012): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /html/Lychee-Laravel/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /html/Lychee-Laravel/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /html/Lychee-Laravel/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 {main}
```

**Comment by ildyria** [comment]
Once this is merged to the master branch of php-exif and updated the vendor folder. This should be fixed. :)

**Comment by ildyria** [comment]
still not fixed (at least not until #452  is merged).

**Comment by ildyria** [comment]
Additionally, once #449 and #452 are merged, I will regenerate a new rc (which might actually be the new official version). :smiley:

**Comment by tmp-hallenser** [comment]
Does the https://github.com/LycheeOrg/php-exif/commit/ca6a366be95b78cc1916ba124bec98ab2f4cbfe7 fix the issue for you? 
I don't get any error message, but the keywords show '?' for Cyrillic symbols.

I did some analysis and came up with the following observations:
* the keywords are encoded as extended ASCII
* `mb_convert_encoding` replaces the Cyrillic symbols with '?' (I guess the encoding is not detected correctly)
*  `utf8_encode` does the job in my case correctly, but will fail on other encodings since it's limited to a specific encoding 
* The library https://packagist.org/packages/neitanod/forceutf8 should hopefully fix this issue (based on a quick test)

Wdyt?

**Comment by tmp-hallenser** [comment]
I've published an branch for php-exif using the forceutf8 lib - please have a look at it.

**Comment by gardiol** [comment]
No the current master does not fix the issue for me. I will try the branch and report here

**Comment by ildyria** [comment]
> No the current master does not fix the issue for me. I will try the branch and report here
> Sorry for late reply, but i am in northern Italy and this is the first time this week i had time to check,

No worries for the late reply. However you do need to do a `composer install` (with or without `--no-dev` is up to you). The change of the code has been done in the dependencies, more precisely in https://github.com/LycheeOrg/php-exif It is not in the main code of the master.
What we did in master is telling that the dependencies have been updated, nothing else.

**Comment by gardiol** [comment]
Well, this is what you get when you stay out of the loop of php development for a few years... Composer is a new mistery for me. Did the install as you told and in fact, it seems to be working great! thank you. I had tons of images not loading...

**Comment by ildyria** [comment]
No problems.
`composer` is just a package manager, just like `apt`, `pacman`, `opam`, `npm` etc... :)
